apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /oauth2
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  name: oauth2-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: auth-proxy.default-tenant.app.vmdev30.lab.iguazeng.com
    http:
      paths:
      - backend:
          service:
            name: oauth2-oauth2-proxy
            port:
              number: 80
        path: /oauth2
        pathType: ImplementationSpecific
