postgresql:
  primary:
    persistence:
      existingClaim: keycloak-pvc
  auth:
    username: iguazio
    password: 24tango
    database: iguazio_keycloak

auth:
  adminUser: iguazio
  adminPassword: 24tango
  managementUser: admin
  managementPassword: 24tango

extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.import=/realm_config/mlrun_realm.json"

extraVolumes:
  - name: realm
    configMap:
      name: mlrun-realm

extraVolumeMounts:
  - name: realm
    mountPath: /realm_config
    readOnly: true

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak-test.default-tenant.app.vmdev30.lab.iguazeng.com
  tls: true
  selfSigned: true
