apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv-test
  labels:
    type: local
spec:
  storageClassName: keycloak
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/iguazio/keycloak_pvc_test"
